spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: jsxl-config-dev
---
spring:
  profiles: test
  application:
    name: jsxl-config-test

---
spring:
  profiles: userprovider
  application:
    name: med-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://101.201.141.142:3306/med              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  #缓存
  redis:
    database: 3
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
      shutdown-timeout: 100
    password: ''
    port: 6379
    timeout: 3600
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.jsxl.med.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/
#       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: med-provider-hystrix-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

topList: med-topList
allList: med-allList

info:
  app:
    name: yyp
    version: $project.version$
