spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: jsxl-config-dev
---
spring:
  profiles: test
  application:
    name: jsxl-config-test
---
spring:
  profiles: userprovider
  application:
    name: med-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://101.201.141.142:3306/med              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  #缓存
  redis:
    database: 3
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
      shutdown-timeout: 100
    password: ''
    port: 6379
    timeout: 3600