spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: jsxl-config-dev
---
spring:
  profiles: test
  application:
    name: jsxl-config-test
---
spring:
  profiles: upr
  application:
    name: med-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://101.201.141.142:3306/med              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时